-- EduScope DEMO_ADMIN Role CHECK 확장
DECLARE
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO V_COUNT
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'APP_ROLE'
       AND CONSTRAINT_NAME = 'CK_APP_ROLE_CODE';

    IF V_COUNT > 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE APP_ROLE DROP CONSTRAINT CK_APP_ROLE_CODE';
    END IF;
END;
/

ALTER TABLE APP_ROLE
ADD CONSTRAINT CK_APP_ROLE_CODE
CHECK (
    ROLE_CODE IN (
        'VIEWER',
        'ANALYST',
        'ADMIN',
        'DEMO_ADMIN'
    )
);
