-- 실행 전 공개용 계정을 EduScope 회원가입 화면에서 먼저 생성한다.
-- 아래 값은 생성한 공개 계정 Login ID로 변경한다.
DEFINE DEMO_LOGIN_ID = 'demo_admin';

-- 공개 계정에 기존 ADMIN 등이 남지 않도록 기존 Role을 제거한다.
DELETE FROM APP_USER_ROLE
WHERE USER_ID = (
    SELECT USER_ID
    FROM APP_USER
    WHERE LOGIN_ID = '&DEMO_LOGIN_ID'
);

-- DEMO_ADMIN Role만 부여한다.
INSERT INTO APP_USER_ROLE (
    USER_ID,
    ROLE_ID,
    ASSIGNED_AT
)
SELECT
    U.USER_ID,
    R.ROLE_ID,
    SYSTIMESTAMP
FROM APP_USER U
CROSS JOIN APP_ROLE R
WHERE U.LOGIN_ID = '&DEMO_LOGIN_ID'
  AND R.ROLE_CODE = 'DEMO_ADMIN';

UPDATE APP_USER
SET
    ACCOUNT_STATUS = 'ACTIVE',
    UPDATED_AT = SYSTIMESTAMP
WHERE LOGIN_ID = '&DEMO_LOGIN_ID';

COMMIT;

SELECT
    U.LOGIN_ID,
    U.DISPLAY_NAME,
    U.ACCOUNT_STATUS,
    R.ROLE_CODE
FROM APP_USER U
JOIN APP_USER_ROLE UR
  ON UR.USER_ID = U.USER_ID
JOIN APP_ROLE R
  ON R.ROLE_ID = UR.ROLE_ID
WHERE U.LOGIN_ID = '&DEMO_LOGIN_ID';
